---
# WHETHER TO USE THE CAMERA SERVER
useCameraServer: false

# PDP
pdp:
  org.usfirst.frc.team449.robot.jacksonWrappers.PDP:
    '@id': PDP
    canID: 0
    voltagePerCurrentLinReg:
      bufferSize: 250
      rSquaredThreshhold: 0.75

# ROBOT SUBSYSTEMS
subsystems:
  # spark test
  - org.usfirst.frc.team449.robot.subsystem.interfaces.binaryMotor.BinaryMotorSimple:
      '@id': amotor
      motor:
        org.usfirst.frc.team449.robot.jacksonWrappers.UPSSparkMax:
          '@id': alsoamotor
          port: 7
          enableBrakeMode: true
      velocity: 0.4


# COMMANDS
commands:
  buttons:
    - button:
        org.usfirst.frc.team449.robot.oi.buttons.SimpleButton:
          '@id': testButton
          joystick:
            org.usfirst.frc.team449.robot.jacksonWrappers.MappedJoystick:
              '@id': joystick
              port: 1
          buttonNumber: 1
      command:
        org.usfirst.frc.team449.robot.subsystem.interfaces.binaryMotor.commands.TurnMotorOn:
          '@id': oncommand
          subsystem:
            org.usfirst.frc.team449.robot.subsystem.interfaces.binaryMotor.BinaryMotorSimple:
              amotor
      action: WHEN_PRESSED
    - button:
        org.usfirst.frc.team449.robot.oi.buttons.SimpleButton:
          '@id': testButton2
          joystick:
            org.usfirst.frc.team449.robot.jacksonWrappers.MappedJoystick:
              joystick
          buttonNumber: 2
      command:
        org.usfirst.frc.team449.robot.subsystem.interfaces.binaryMotor.commands.TurnMotorOff:
          '@id': offcommand
          subsystem:
            org.usfirst.frc.team449.robot.subsystem.interfaces.binaryMotor.BinaryMotorSimple:
              amotor
      action: WHEN_PRESSED
# UPDATER
updater:
  org.usfirst.frc.team449.robot.other.Updater:
    '@id': updater
    updatables:
      - org.usfirst.frc.team449.robot.jacksonWrappers.PDP: PDP