---
# WHETHER TO USE THE CAMERA SERVER
useCameraServer: false

# PDP
pdp:
  org.usfirst.frc.team449.robot.jacksonWrappers.PDP:
    '@id': PDP
    canID: 0
    voltagePerCurrentLinReg:
      bufferSize: 250
      rSquaredThreshhold: 0.75

# ROBOT SUBSYSTEMS
subsystems:
  # SHOOTER
  - org.usfirst.frc.team449.robot.subsystem.complex.shooter.LoggingFlywheel:
      '@id': shooterFlywheel
      shooterMotor:
        org.usfirst.frc.team449.robot.jacksonWrappers.FPSSparkMax:
          '@id': shooterMotor
          port: 1 #TODO
          name: shooterMotor
          reverseOutput: false
          enableBrakeMode: false
          #          vfpspoltagePerCurrentLinReg: 0 #TODO
          PDP: PDP
          #          fwdLimitSwitchNormallyOpen: false #TODO
          #          revLimitSwitchNormallyOpen: false #TODO
          #          remoteLimitSwitchID: 0 #TODO
          #fwdSoftLimit: 0 #TODO
          #revSoftLimit: 0 # TODO
          #          postEncoderGearing: 1 #TODO
          feetPerRotation: 0 #TODO
          currentLimit: 5 #TODO
          enableVoltageComp: true #TODO
          #          voltageCompSamples: 100 #TODO
          reverseSensor: false #TODO
          #          perGearSettings:
          #            - gearNum: 0
          #              kP: 0.003
          #              kI: 0.0
          #              kD: 0.05
          #              #TODO check these values, currently same as kP, etc
          #              posKP: 0.003
          #              posKI: 0.0
          #              posKD: 0.05
          startingGearNum: 0 #TODO
      #          ###slaveVictors:
      #          ###  - port: 3 #TODO
      #          ###    invertType: OpposeMaster
      shooterThrottle: 0.2 #TODO
      kickerMotor:
        org.usfirst.frc.team449.robot.jacksonWrappers.FPSTalon: #TODO TODO
          '@id': kickerTalon
          port: 2 #TODO
          name: kickerTalon
          reverseOutput: false
          enableBrakeMode: false
          #voltagePerCurrentLinReg: 0 #TODO
          PDP: PDP
          #fwdLimitSwitchNormallyOpen: false #TODO
          #revLimitSwitchNormallyOpen: false #TODO
          #remoteLimitSwitchID: 0 #TODO
          #fwdSoftLimit: 0 #TODO
          #revSoftLimit: 0 # TODO
          #          postEncoderGearing: 0 #TODO
          #feetPerRotation: 0 #TODO
          currentLimit: 10 #TODO
          #enableVoltageComp: true #TODO
          #          voltageCompSamples: 100 #TODO
          #          feedbackDevice: QuadEncoder #TODO
          #          encoderCPR: 256 #TODO
          reverseSensor: false #TODO
          #          perGearSettings:
          #            - gearNum: 0
          #              kP: 0.003
          #              kI: 0.0
          #              kD: 0.05
          #              #TODO check these values, currently same as kP, etc
          #              posKP: 0.003
          #              posKI: 0.0
          #              posKD: 0.05
          startingGearNum: 0 #TODO
      feederThrottle: 0.1 #TODO
      spinUpTimeoutSecs: 2
      minShootingSpeedFPS: 1
  # FEEDER
  - org.usfirst.frc.team449.robot.subsystem.interfaces.intake.IntakeSimple:
      '@id': feeder
      motor:
        org.usfirst.frc.team449.robot.jacksonWrappers.FPSTalon: #TODO TODO
          '@id': feederMotor
          port: 2 #TODO
          name: feederMotor
          reverseOutput: false
          enableBrakeMode: false
          #voltagePerCurrentLinReg: 0 #TODO
          PDP: PDP
          #fwdLimitSwitchNormallyOpen: false #TODO
          #revLimitSwitchNormallyOpen: false #TODO
          #remoteLimitSwitchID: 0 #TODO
          #fwdSoftLimit: 0 #TODO
          #revSoftLimit: 0 # TODO
          #          postEncoderGearing: 0 #TODO
          #feetPerRotation: 0 #TODO
          currentLimit: 10 #TODO
          #enableVoltageComp: true #TODO
          #          voltageCompSamples: 100 #TODO
          #          feedbackDevice: QuadEncoder #TODO
          #          encoderCPR: 256 #TODO
          reverseSensor: false #TODO
          #          perGearSettings:
          #            - gearNum: 0
          #              kP: 0.003
          #              kI: 0.0
          #              kD: 0.05
          #              #TODO check these values, currently same as kP, etc
          #              posKP: 0.003
          #              posKI: 0.0
          #              posKD: 0.05
          startingGearNum: 0 #TODO
      inSlowVel: 0.1
      inFastVel: 0.2
      outSlowVel: -0.1
      outFastVel: -0.2
  # INTAKE
  - org.usfirst.frc.team449.robot.subsystem.interfaces.intake.IntakeSimple:
      '@id': intake
      motor:
        org.usfirst.frc.team449.robot.jacksonWrappers.FPSTalon: #TODO TODO
          '@id': intakeMotor
          port: 2 #TODO
          name: intakeMotor
          reverseOutput: false
          enableBrakeMode: false
          #voltagePerCurrentLinReg: 0 #TODO
          PDP: PDP
          #fwdLimitSwitchNormallyOpen: false #TODO
          #revLimitSwitchNormallyOpen: false #TODO
          #remoteLimitSwitchID: 0 #TODO
          #fwdSoftLimit: 0 #TODO
          #revSoftLimit: 0 # TODO
          #          postEncoderGearing: 0 #TODO
          #feetPerRotation: 0 #TODO
          currentLimit: 10 #TODO
          #enableVoltageComp: true #TODO
          #          voltageCompSamples: 100 #TODO
          #          feedbackDevice: QuadEncoder #TODO
          #          encoderCPR: 256 #TODO
          reverseSensor: false #TODO
          #          perGearSettings:
          #            - gearNum: 0
          #              kP: 0.003
          #              kI: 0.0
          #              kD: 0.05
          #              #TODO check these values, currently same as kP, etc
          #              posKP: 0.003
          #              posKI: 0.0
          #              posKD: 0.05
          startingGearNum: 0 #TODO
      inSlowVel: 0.1
      inFastVel: 0.2
      outSlowVel: -0.1
      outFastVel: -0.2

# COMMANDS
commands:
  #BUTTONS

  #        org.usfirst.frc.team449.robot.subsystem.interfaces.flywheel.commands.SpinUpFlywheel:
  buttons:
    - button:
        org.usfirst.frc.team449.robot.oi.buttons.SimpleButton:
          '@id': shooterStartButton
          joystick:
            org.usfirst.frc.team449.robot.jacksonWrappers.MappedJoystick:
              '@id': mechanismsJoystick
              port: 2 #TODO
          buttonNumber: 1 #A
      command:
        org.usfirst.frc.team449.robot.commands.general.MappedSequentialCommandGroup:
          commands:
            - org.usfirst.frc.team449.robot.subsystem.interfaces.flywheel.commands.SpinUpFlywheel:
                '@id': spinUpFlywheelCommand1
                flywheel:
                  org.usfirst.frc.team449.robot.subsystem.complex.shooter.LoggingFlywheel: shooterFlywheel
                feeder:
                  org.usfirst.frc.team449.robot.subsystem.interfaces.intake.IntakeSimple:
                    feeder
            - org.usfirst.frc.team449.robot.subsystem.interfaces.flywheel.commands.SpinUpFlywheelUntilIntakeStops:
                spinUpFlywheelCommand:
                  org.usfirst.frc.team449.robot.subsystem.interfaces.flywheel.commands.SpinUpFlywheel:
                    '@id': spinUpFlywheelCommand2
                    flywheel:
                      org.usfirst.frc.team449.robot.subsystem.complex.shooter.LoggingFlywheel: shooterFlywheel
                    feeder:
                      org.usfirst.frc.team449.robot.subsystem.interfaces.intake.IntakeSimple:
                        feeder
                shooterFlywheel: shooterFlywheel
                feeder: feeder

      action: WHEN_PRESSED
    - button:
        org.usfirst.frc.team449.robot.oi.buttons.SimpleButton:
          '@id': shooterStopButton
          joystick:
            org.usfirst.frc.team449.robot.jacksonWrappers.MappedJoystick:
              mechanismsJoystick
          buttonNumber: 2 #B
      command:
        org.usfirst.frc.team449.robot.subsystem.interfaces.flywheel.commands.TurnAllOffWithRequires:
          '@id': shooterStopCommand
          subsystem:
            org.usfirst.frc.team449.robot.subsystem.complex.shooter.LoggingFlywheel:
              shooterFlywheel
      action: WHEN_PRESSED
    - button:
        org.usfirst.frc.team449.robot.oi.buttons.SimpleButton:
          '@id': intakeToggleButton
          joystick:
            org.usfirst.frc.team449.robot.jacksonWrappers.MappedJoystick:
              mechanismsJoystick
          buttonNumber: 3 #X
      command:
        org.usfirst.frc.team449.robot.subsystem.interfaces.intake.commands.ToggleIntaking:
          '@id': feederToggleCommand
          subsystem:
            org.usfirst.frc.team449.robot.subsystem.interfaces.intake.IntakeSimple:
              feeder
          mode: IN_FAST
      action: WHEN_PRESSED
    - button:
        org.usfirst.frc.team449.robot.oi.buttons.SimpleButton:
          '@id': intakeStartButton
          joystick:
            org.usfirst.frc.team449.robot.jacksonWrappers.MappedJoystick:
              mechanismsJoystick
          buttonNumber: 4 #Y
      command:
        org.usfirst.frc.team449.robot.subsystem.interfaces.intake.commands.SetIntakeMode:
          '@id': intakeStartCommand
          subsystem:
            org.usfirst.frc.team449.robot.subsystem.interfaces.intake.IntakeSimple:
              intake
          mode: IN_FAST
      action: WHEN_PRESSED
  # DEFAULT COMMANDS
  defaultCommands:
  # DEFAULT DRIVE COMMAND
#      - subsystem:
#          org.usfirst.frc.team449.robot.drive.unidirectional.DriveUnidirectionalWithGyroShiftable:
#            drive
#        command:
#          org.usfirst.frc.team449.robot.commands.multiInterface.drive.UnidirectionalNavXShiftingDefaultDrive:
#            '@id': defaultDriveCommand
#            kP: 0.003
#            kI: 0.0
#            kD: 0.05
#            absoluteTolerance: 0
#            deadband: 2
#            maxAngularVelToEnterLoop: 3
#            inverted: false
#            highGearAngularCoefficient: 3
#            rampComponent:
#              org.usfirst.frikc.team449.robot.generalInterfaces.doubleUnaryOperator.RampComponent:
#                maxIncreasePerSecond: 3
#                maxDecreasePerSecond: 1.5
#            driveStraightLoopEntryTimer:
#              '@id': driveStraightLoopEntryTimer
#              bufferTimeSeconds: 0.15
#            subsystem:
#              org.usfirst.frc.team449.robot.drive.unidirectional.DriveUnidirectionalWithGyroShiftable:
#                drive
#            oi:
#              org.usfirst.frc.team449.robot.oi.unidirectional.arcade.OIArcadeWithDPad:
#                '@id': oi
#                gamepad:
#                  org.usfirst.frc.team449.robot.jacksonWrappers.MappedJoystick:
#                    '@id': driverGamepad
#                    port: 1
#                rotThrottle:
#                  org.usfirst.frc.team449.robot.oi.throttles.ThrottlePolynomial:
#                    &rotThrottle
#                    '@id': rotThrottle
#                    stick: driverGamepad
#                    axis: 0
#                    smoothingTimeSecs: 0.04
#                    deadband: 0.08
#                    inverted: false
#                    polynomial:
#                      org.usfirst.frc.team449.robot.generalInterfaces.doubleUnaryOperator.Polynomial:
#                        '@id': rotPoly
#                        powerToCoefficientMap: !!map
#                          1: .5
#                          3: .5
#                    scale: .7
#                fwdThrottle:
#                  org.usfirst.frc.team449.robot.oi.throttles.ThrottleSum:
#                    '@id': fwdThrottle
#                    throttles:
#                      - org.usfirst.frc.team449.robot.oi.throttles.ThrottlePolynomial:
#                          <<: *rotThrottle
#                          '@id': posThrottle
#                          axis: 3
#                          inverted: false
#                          deadband: 0.05
#                          polynomial:
#                            org.usfirst.frc.team449.robot.generalInterfaces.doubleUnaryOperator.Polynomial:
#                              '@id': posPoly
#                              powerToCoefficientMap: !!map
#                                1: 2
#                                3: 1
#                      - org.usfirst.frc.team449.robot.oi.throttles.ThrottlePolynomial:
#                          <<: *rotThrottle
#                          '@id': negThrottle
#                          axis: 2
#                          inverted: true
#                          deadband: 0.05
#                          polynomial:
#                            org.usfirst.frc.team449.robot.generalInterfaces.doubleUnaryOperator.Polynomial:
#                              '@id': negPoly
#                              powerToCoefficientMap: !!map
#                                1: 2
#                                3: 1
#                invertDPad: false
#                dPadShift: 0.1
#                turnInPlaceRotScale: 0.5
#                rescaleOutputs: true
#                scaleRotByFwdPoly:
#                  org.usfirst.frc.team449.robot.generalInterfaces.doubleUnaryOperator.Polynomial:
#                    '@id': scaleRotByFwdPoly
#                    powerToCoefficientMap: !!map
#                      0.5: 0.4
#                      0: 0.2
#                      #1 : 0.25
#                      #2: 0.25
#            autoshiftComponent:
#              '@id': autoshiftComponent
#              upshiftSpeed: 4
#              downshiftSpeed: 2.7
#              upshiftDebouncer:
#                '@id': upshiftDebouncer
#                bufferTimeSeconds: 0.06
#              upshiftFwdThresh: 0.4
#    autoStartupCommand:
#      org.usfirst.frc.team449.robot.commands.multiInterface.drive.RamseteControllerUnidirectionalDrive:
#        '@id':testDriveCommand
#        drivetrain:
#          org.usfirst.frc.team449.robot.drive.unidirectional.DriveUnidirectionalWithGyroShiftable: drive
#        P: 0.15
#        D: 0

# UPDATER
updater:
  org.usfirst.frc.team449.robot.other.Updater:
    '@id': updater
    updatables:
      #      - org.usfirst.frc.team449.robot.drive.unidirectional.DriveUnidirectionalWithGyroShiftable: drive
      #      - org.usfirst.frc.team449.robot.oi.unidirectional.arcade.OIArcadeWithDPad: oi
      #      - org.usfirst.frc.team449.robot.jacksonWrappers.MappedAHRS: navX
      - org.usfirst.frc.team449.robot.jacksonWrappers.PDP: PDP
